
import { EdgeStoreProvider } from "@/lib/edgestore";

export const metadata = {
  title: "admin",
  description: "Generated by create next app",
};

export default function BlogLayout({ children }) {
  return (
    <EdgeStoreProvider>
     {children}
    </EdgeStoreProvider>
  );
}
