import { CustomCursor, FluidCanvas, SmoothScroll } from "@/components/custom";
import "./globals.css";
import Loader from "@/components/common/Loader/Loader";
import { Header } from "@/components/common";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased overflow-x-hidden bg-black! text-black">
        <Loader />
        {/* <FluidCanvas />     */}
        <Header />
        <SmoothScroll>{children}</SmoothScroll>
        <CustomCursor />
      </body>
    </html>
  );
}
