export default {
  brightness: 0.5,
  backgroundColor: "#000000",
  colorPalette: ["#4e14dd", "#ff007a"],
  colorRandomness: 0,
  inverted: false,
  simResolution: 30,
  dyeResolution: 512,
  densityDissipation: 1,
  velocityDissipation: 0.1,
  pressureIterations: 0.3,
  splatRadius: 0.2,
  curl: 1,
  startSplats: 2,
  splatAmount: 3,
  trigger: "move",
  hover: false,
};
