import { SmoothScroll } from "@/custom";
import { EdgeStoreProvider } from "@/lib/edgestore";

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function BlogLayout({ children }) {
  return (
    <EdgeStoreProvider>
      <SmoothScroll>{children}</SmoothScroll>
    </EdgeStoreProvider>
  );
}
