import { SmoothScroll } from "@/custom";


export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function BlogLayout({ children }) {
  return <SmoothScroll>{children}</SmoothScroll>;
}
