export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function BlogLayout({ children }) {
  return (
    <div className="flex justify-center">
      {children}
    </div>
  );
}
